package servent.message;

public enum MessageType {
	POISON, TRANSACTION,
	CC_SNAPSHOT_REQUEST, CC_ACK, CC_RESUME,
	AB_TOKEN, AB_ACK,
	ACHARYA_BADRINATH_ASK_AMOUNT, ACHARYA_BADRINATH_TELL_AMOUNT,
	AB_AV
}
